### ISSUE TITLE
Design Issue on IPhone 15

### ISSUE THREAD

**Issue by 1olelllka** [1olelllka/ExpressNews#1]
<img width="310" alt="Screenshot 2024-05-07 at 20 37 54" src="https://github.com/1olelllka/ExpressNews/assets/67587036/3347efc9-bf20-4f46-8566-3f6cbb730c72">

Just make some mircrofix plz. Idk if this problem appears on your vm.

**Comment by 1olelllka** [comment]
**That's the login page**
I haven't seen the same problem on signup page

**Comment by geno3a** [comment]
fixed

**Comment by geno3a** [comment]
fixed
